### ISSUE TITLE
About `n_iter`, to align with others

### ISSUE THREAD

**Issue by userElaina** [fra31/auto-attack#106]
Hi! Thank you for your work and code!

In this algorithm, the number of iterations is "free". To align with other algorithms (like PGD, CW), I want to modify the number of iterations in this algorithm.

Is there any guide for that?

Or, I tried editing `n_iter=xxx` directly in `autoattack/autoattack.py` (commit [d2551ea](https://github.com/workelaina/autoatk/commit/d2551ea491edce5ad2fb2767f1977a9426df5dda) in my fork). Will this seriously break the algorithm?

**Comment by ScarlettChan** [comment]
您好，您的邮件已收到!

**Comment by fra31** [comment]
Hi,

your solution should work fine. If you (largely) change the number of queries in Square Attack, you might want to set `resc_schedule=True`. Please note the performance might vary if you significantly reduce the number of iterations (especially for the black-box Square Attack).

**Comment by userElaina** [comment]
OK, thank you for your reply.

**Comment by ScarlettChan** [comment]
您好，您的邮件已收到!
