### ISSUE TITLE
Evaluation on randomized defenses

### ISSUE THREAD

**Issue by chawins** [fra31/auto-attack#15]
I see that the attack is modified slightly for the non-deterministic defenses. I could not find part of the code that handles this setting. Could you point me to the code or please make it available? Thank you!

**Comment by fra31** [comment]
Hi,

for randomized defenses the main difference is using APGD with Expectation over Transformations (EoT), and using the untargeted losses. To set the number of estimations of the gradient over which taking the average, one can modify the value of `eot_iter` [here](https://github.com/fra31/auto-attack/blob/db61899c61264a3ede1cb4abacd104b0c192fe13/autopgd_pt.py#L27) (we use 20 in the paper).

I will add a specific option to set this automatically as soon as possible. Temporarily, if you initialize the attack with `version='custom'` and then add
```python
adversary.attacks_to_run = ['apgd-ce', 'apgd-dlr']
adversary.apgd.n_restarts = 1
adversary.apgd.eot_iter = 20
```
you should get the evaluation with EoT. The modification to use Square for randomized defenses is not included in the code at the moment, but in our experiments APGD is anyway the most effective attack in this case.

Let me know if this works for you!

**Comment by chawins** [comment]
Sounds great! Thank you.
