### ISSUE TITLE
Interested in adding models to the table!

### ISSUE THREAD

**Issue by chawins** [fra31/auto-attack#17]
Is it still possible to have new models added to the table? I remember seeing some template earlier, but it seems to have been removed. What is the current protocol? Or is it a work in progress at the moment?

**Comment by fra31** [comment]
Hi,

sure, we keep adding models. You're right, the [template](https://github.com/fra31/auto-attack/tree/master/autoattack/.github/ISSUE_TEMPLATE) has been accidentally moved and is not shown anymore, I'll fix this. You can also check [this](https://github.com/fra31/auto-attack/issues/7) for reference.

**Comment by fra31** [comment]
The template should be back now. It's mainly a guideline, you don't need to fill all the fields to submit the new model.
