### ISSUE TITLE
Add Adversarial Training with Early Stopping (ATES), CIFAR-100

### ISSUE THREAD

**Issue by chawins** [fra31/auto-attack#22]
**Paper**: Improving Adversarial Robustness Through Progressive Hardening [https://arxiv.org/abs/2003.09347](https://arxiv.org/abs/2003.09347)

**Venue**: under review

**Dataset and threat model**: CIFAR-100, L-inf, 8/255

**Code**: [https://github.com/chawins/ates-minimal](https://github.com/chawins/ates-minimal)

**Pre-trained model**: [weight](https://berkeley.box.com/shared/static/b1t0613tw7bhkvojkihijqghebxsqcpf.pt)

**Log file**: [log](https://github.com/chawins/ates-minimal/blob/master/test_cifar100-wrn_09-29-2020-18:58:24.log)

**Additional data**: no

**Clean and robust accuracy**: 62.82/24.57

**Architecture**: WRN-34-10

**Description of the model/defense**: We use the curriculum learning framework to schedule the "difficulty" of adversarial examples generated during adversarial training. This improves both clean and robust accuracy.

**Comment by fra31** [comment]
Hi,

thanks for the submission! I could reproduce the results you report and I'm happy to add you model!

**Comment by chawins** [comment]
Thank you!
