### ISSUE TITLE
Add Adversarial Training with Early Stopping (ATES), CIFAR-10

### ISSUE THREAD

**Issue by chawins** [fra31/auto-attack#23]
**Paper**: Improving Adversarial Robustness Through Progressive Hardening [https://arxiv.org/abs/2003.09347](https://arxiv.org/abs/2003.09347)

**Venue**: under review

**Dataset and threat model**: CIFAR-10, L-inf, 8/255

**Code**: [https://github.com/chawins/ates-minimal](https://github.com/chawins/ates-minimal)

**Pre-trained model**: [weight](https://berkeley.box.com/shared/static/hgehswlmggrs5si9ziia2uuquxtngvd2.pt)

**Log file**: [log](https://github.com/chawins/ates-minimal/blob/master/test_cifar10-wrn_09-30-2020-01:47:42.log)

**Additional data**: no

**Clean and robust accuracy**: 86.84/50.72

**Architecture**: WRN-34-10

**Description of the model/defense**: We use the curriculum learning framework to schedule the "difficulty" of adversarial examples generated during adversarial training. This improves both clean and robust accuracy.

**Comment by fra31** [comment]
Hi,

thanks for the submission! I could reproduce the results you report and I'm happy to add your model!

**Comment by chawins** [comment]
Thank you!
