### ISSUE TITLE
Add AWP w/o additional data

### ISSUE THREAD

**Issue by csdongxian** [fra31/auto-attack#27]
**Paper**: Dongxian Wu, Shu-Tao Xia, Yisen Wang. Adversarial Weight Perturbation Helps Robust Generalization

**Venue**: NeurIPS 2020

**Dataset and threat model**: CIFAR-10/CIFAR100 under L-inf (8/255) and CIFAR-10 under L-2 (0.5)

**Code**: https://github.com/csdongxian/AWP/tree/main/auto_attacks

**Pre-trained model**:
 [CIFAR-10 under L_inf](https://drive.google.com/file/d/1hlVTLZkveYGWpE9-46Wp5NVZt1slz-1T/view?usp=sharing)
 [CIFAR-100 under L_inf](https://drive.google.com/file/d/1aUQ3Udbn-zfQENwHRe8JsmkxjIcq0zVU/view?usp=sharing)
 [CIFAR-10 under L_2](https://drive.google.com/file/d/1D-QCH-0ShtFo0s6gke5y6Ix7_x6k4Bys/view?usp=sharing)

**Log file**:
[CIFAR-10 under L_inf](https://github.com/csdongxian/AWP/blob/main/auto_attacks/logs/log_TRADES-AWP_cifar10_linf_WRN34-10.txt)
[CIFAR-100 under L_inf](https://github.com/csdongxian/AWP/blob/main/auto_attacks/logs/log_AT-AWP_cifar100_linf_wrn34-10.txt)
[CIFAR-10 under L_2](https://github.com/csdongxian/AWP/blob/main/auto_attacks/logs/log_TRADES-AWP_cifar10_l2_wrn34-10.txt)

**Additional data**: no

**Clean and robust accuracy**: 
CIFAR-10 under L_inf: 85.36% / 56.17%
CIFAR-100 under L_inf: 60.38% / 28.86%
CIFAR-10 under L_2: 88.51% / 73.66%

**Architecture**: WRN-34-10

**Description of the model/defense**:  We introduce adversarial weight perturbations to adversarial training and its variants (TRADES, MART, RST, etc.), which can help the robust generalization.

**Comment by fra31** [comment]
Hi,

thanks for the submission! I've added the models!

**Comment by csdongxian** [comment]
Thank you!
