### ISSUE TITLE
Add AWP w/ additional data

### ISSUE THREAD

**Issue by csdongxian** [fra31/auto-attack#28]
**Paper**: Dongxian Wu, Shu-Tao Xia, Yisen Wang. Adversarial Weight Perturbation Helps Robust Generalization

**Venue**: NeurIPS 2020

**Dataset and threat model**: CIFAR-10, L-inf, 8/255

**Code**: https://github.com/csdongxian/AWP/tree/main/auto_attacks

**Pre-trained model**: [weight](https://drive.google.com/file/d/1sSjh4i2imdoprw_JcPj2cZzrJm0RIRI6/view?usp=sharing)

**Log file**: [log](https://github.com/csdongxian/AWP/blob/main/auto_attacks/logs/log_RST-AWP_cifar10_linf_WRN28-10.txt)

**Additional data**: yes

**Clean and robust accuracy**: 88.25% / 60.04%

**Architecture**: WRN-28-10

**Description of the model/defense**:  We introduce adversarial weight perturbations to adversarial training and its variants (TRADES, MART, RST, etc.), which can help the robust generalization.

**Comment by fra31** [comment]
Hi,

thanks for the submission! I've added your model!

**Comment by csdongxian** [comment]
Thank you!
