### ISSUE TITLE
Unable to customize attacks' parameters 

### ISSUE THREAD

**Issue by CNOCycle** [fra31/auto-attack#31]
Hi, authors

I notice that some issues when I customize attacks. 

First, `attacks_to_run` or some basic parameters are set at the beginning and `set_version` is called at the end of constructor.

https://github.com/fra31/auto-attack/blob/8af30a9fc43f5c4f5db702fe696ecb0fedbc2ba9/autoattack/autoattack.py#L10-L24

https://github.com/fra31/auto-attack/blob/8af30a9fc43f5c4f5db702fe696ecb0fedbc2ba9/autoattack/autoattack.py#L60-L61

Therefore, those parameters are overwritten by `set_version`.

Second, the detailed of configuration are set in `set_version`. 

https://github.com/fra31/auto-attack/blob/8af30a9fc43f5c4f5db702fe696ecb0fedbc2ba9/autoattack/autoattack.py#L229-L251

I would suggest that public APIs are required in order to set the detailed.

**Comment by fra31** [comment]
Hi,

you're right, `set_version` overwrites the parameters parsed at initialization. However, this happens only when a predefined version is given https://github.com/fra31/auto-attack/blob/8af30a9fc43f5c4f5db702fe696ecb0fedbc2ba9/autoattack/autoattack.py#L60

If you want to use custom parameters, you can for example initialize the attack with `version='custom'`, which will not call `set_version` and set some default version.
Alternatively, you can change the parameters after initialization like https://github.com/fra31/auto-attack/blob/8af30a9fc43f5c4f5db702fe696ecb0fedbc2ba9/autoattack/examples/eval.py#L57-L60

The idea of `set_version` is to have standard versions, whose parameters  are not set manually.
I understand that it could change the parsed parameters unexpectedly. Maybe I could add a message when `set_version` is called: could this work? Or do you have other suggestions?

**Comment by CNOCycle** [comment]
I agree.  But, some cases still are not covered. For example, I cannot launch fab attack on L1 norm `norm="L1", attacks_to_run=['fab']`.

What I do now is overriding `set_version` and checking whether the parameters is set correctly,

**Comment by fra31** [comment]
True. We plan to add an L1-version (hopefully soon), then that case would be covered. In the meantime, I'll add the message I mentioned to improve clarity.
