### ISSUE TITLE
Normalized input data for AutoAttack

### ISSUE THREAD

**Issue by Liang-Shang** [fra31/auto-attack#46]
Hi authors,

If our models for CIFAR-10 are trained with normalized data on CIFAR-10 (mean=(0.4914, 0.4822, 0.4465), std=(0.2023, 0.1994, 0.2010)), are we able to evaluate the robust accuracy through your AutoAttack? Because I could not find a normalized neither in eval.py nor in autoattack.py.

Thanks,
Liang

**Comment by fra31** [comment]
Hi,

since the attacks expect inputs in [0, 1]^d, any normalization has to be included in the model definition. A possible solution is here https://github.com/fra31/auto-attack/issues/13.

Hope this helps!

**Comment by Liang-Shang** [comment]
Thanks for letting me know that. This looks great!
