### ISSUE TITLE
Normalization of CIFAR-10 images

### ISSUE THREAD

**Issue by GeJulia** [fra31/auto-attack#53]
In your script, you didn't use the standard normalization done on CIFAR-10. Would you say that a fair comparison is still given, even when normalization is applied? Or should an approach tested by AutoAttack be trained without this normalization to stay comparable?
Best regards, and thanks for offering this great repo for testing robustness!

**Comment by fra31** [comment]
Hi,

I guess you have found them, but, if not, see https://github.com/fra31/auto-attack/issues/13 and https://github.com/fra31/auto-attack/issues/16.

**Comment by GeJulia** [comment]
Hi, 
yes I saw the previous issue this is why I closed it directly. 
But still, thanks!
