### ISSUE TITLE
Why do you evaluate your model without standard mean and standard variance normalization?

### ISSUE THREAD

**Issue by jS5t3r** [fra31/auto-attack#55]
In this file:
https://github.com/fra31/auto-attack/blob/master/autoattack/examples/eval.py 
line 37 there is the transform statement without normalization...

I am wondering if you have trained the model without normalization, too?

**Comment by fra31** [comment]
Hi,

the attacks expect images with elements in [0, 1]. Any normalization should be included in the forward pass (see also https://github.com/fra31/auto-attack/issues/13 and https://github.com/fra31/auto-attack/issues/16).
