### ISSUE TITLE
Update AutoAttack Framework to pytorch 1.9

### ISSUE THREAD

**Issue by jS5t3r** [fra31/auto-attack#68]
Hi, 

aa new PyTroch version is released: https://pytorch.org/blog/pytorch-1.9-released/

It showed me while training models, that training time goes down by a factor of 2 or 3...

When using your Framework, some updates are needed. 

I would like to push my updates to this repository.  Can I have a branch or something like that?

regards
Peter

**Comment by fra31** [comment]
Hi,

that'd be very useful, thanks! What about forking the repository and opening a pull request?

**Comment by jS5t3r** [comment]
Ok. That's fine.
