### ISSUE TITLE
TF2 implementation

### ISSUE THREAD

**Issue by CNOCycle** [fra31/auto-attack#8]
Hi authors,

I sincerely thank all authors for their time and efforts. Auto-attack is a powerful tool which helping me checking defense's robustness.

After reading the source code, I only fond APIs for TF1. The latest version of TF1(tf-1.15.0) published in 6 months ago. I thought that APIs should be upgraded to support TF2.

I am willing to implement APIs for TF2 if necessary.

Thanks

**Comment by fra31** [comment]
Hi,

glad that you find AutoAttack useful!

I agree that it's important to be compatible with TF2. I think `utils_tf.py` is the only file which requires to be updated. If you implemented it, your contribution would be more than welcome, so feel free to open a PR! I'm also available for any discussion if needed.

Thanks!
